version: '3.7'
services:
  nginx:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  painel:
    image: ghcr.io/sdw-for-all/painel:latest
    container_name: painel
    expose:
      - "80"
    restart: always
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
